POST http://localhost:1234/normal
Content-Type: multipart/form-data; boundary=---------------------------2102512801813682967680946991

--boundary123
Content-Disposition: form-data; name="username"

Cem Gülümsér
--boundary123
Content-Disposition: form-data; name="profile_pic"; filename="example.txt"
Content-Type: text/plain

This is a small example file content.') or true--
--boundary123--


