POST http://localhost:1234/normal
Content-Type: text/javascript

document.addEventListener('DOMContentLoaded', function() {
    const button = document.getElementById('myButton');
    button.addEventListener('click', function() {
        alert(' AS INJECTX WHERE 1=1 AND 1=0--was clicked!');
    });
});